name: login_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Sofia-Pro
      fonts:
        - asset: assets/fonts/sofia-pro-ultralight.otf
          weight: 200
        - asset: assets/fonts/sofia-pro-light.otf
          weight: 300
        - asset: assets/fonts/sofia-pro-regular.otf
          weight: 400
        - asset: assets/fonts/sofia-pro-medium.otf
          weight: 500
        - asset: assets/fonts/sofia-pro-semibold.otf
          weight: 600
        - asset: assets/fonts/sofia-pro-bold.otf
          weight: 700
        - asset: assets/fonts/sofia-pro-black.otf
          weight: 900
  assets:
    - assets/images/
