name: drinkup_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.2
  loading_indicator: ^3.1.1
  async: ^2.11.0
  web_socket_channel: ^2.4.0
  go_router: ^12.1.3
  dio: ^5.4.0
  flutter_secure_storage: ^9.0.0
  equatable: ^2.0.5
  meta: ^1.10.0
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  connectivity_plus: ^5.0.2
  internet_connection_checker: ^1.0.0+1
  shared_preferences: ^2.2.2
  flutter_native_splash: ^2.3.9
  flutter_displaymode: ^0.6.0
  rename: ^3.0.1

flutter_native_splash:
  background_image: "assets/images/splash-water-001.png"
  android_12:
    color: "#ffffff"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  fonts:
    - family: Sofia-Pro
      fonts:
        - asset: assets/fonts/sofia-pro-ultralight.otf
          weight: 200
        - asset: assets/fonts/sofia-pro-light.otf
          weight: 300
        - asset: assets/fonts/sofia-pro-regular.otf
          weight: 400
        - asset: assets/fonts/sofia-pro-medium.otf
          weight: 500
        - asset: assets/fonts/sofia-pro-semibold.otf
          weight: 600
        - asset: assets/fonts/sofia-pro-bold.otf
          weight: 700
        - asset: assets/fonts/sofia-pro-black.otf
          weight: 900
  assets:
    - assets/images/
